/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDevelopmentCourseOnlineRouteImport } from './routes/web-development-course-online'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PythonCourseOnlineRouteImport } from './routes/python-course-online'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PhysicsTutorRouteImport } from './routes/physics-tutor'
import { Route as OnlineTutorServicePakistanRouteImport } from './routes/online-tutor-service-pakistan'
import { Route as OnlineClassesForStudentsRouteImport } from './routes/online-classes-for-students'
import { Route as MathsTutorRouteImport } from './routes/maths-tutor'
import { Route as InternationalOnlineAcademyRouteImport } from './routes/international-online-academy'
import { Route as Grade5ToMsOnlineLearningRouteImport } from './routes/grade-5-to-ms-online-learning'
import { Route as FreeDemoRouteImport } from './routes/free-demo'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComputerScienceTutoringRouteImport } from './routes/computer-science-tutoring'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutoringIndexRouteImport } from './routes/tutoring.index'
import { Route as SpecializationsIndexRouteImport } from './routes/specializations.index'
import { Route as LiveBatchesIndexRouteImport } from './routes/live-batches.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as SpecializationsSlugRouteImport } from './routes/specializations.$slug'
import { Route as LiveBatchesSlugRouteImport } from './routes/live-batches.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as ApiAdmissionsRouteImport } from './routes/api.admissions'

const WebDevelopmentCourseOnlineRoute =
  WebDevelopmentCourseOnlineRouteImport.update({
    id: '/web-development-course-online',
    path: '/web-development-course-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonCourseOnlineRoute = PythonCourseOnlineRouteImport.update({
  id: '/python-course-online',
  path: '/python-course-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsTutorRoute = PhysicsTutorRouteImport.update({
  id: '/physics-tutor',
  path: '/physics-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineTutorServicePakistanRoute =
  OnlineTutorServicePakistanRouteImport.update({
    id: '/online-tutor-service-pakistan',
    path: '/online-tutor-service-pakistan',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineClassesForStudentsRoute =
  OnlineClassesForStudentsRouteImport.update({
    id: '/online-classes-for-students',
    path: '/online-classes-for-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const MathsTutorRoute = MathsTutorRouteImport.update({
  id: '/maths-tutor',
  path: '/maths-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalOnlineAcademyRoute =
  InternationalOnlineAcademyRouteImport.update({
    id: '/international-online-academy',
    path: '/international-online-academy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Grade5ToMsOnlineLearningRoute =
  Grade5ToMsOnlineLearningRouteImport.update({
    id: '/grade-5-to-ms-online-learning',
    path: '/grade-5-to-ms-online-learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const FreeDemoRoute = FreeDemoRouteImport.update({
  id: '/free-demo',
  path: '/free-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerScienceTutoringRoute = ComputerScienceTutoringRouteImport.update({
  id: '/computer-science-tutoring',
  path: '/computer-science-tutoring',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoringIndexRoute = TutoringIndexRouteImport.update({
  id: '/tutoring/',
  path: '/tutoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsIndexRoute = SpecializationsIndexRouteImport.update({
  id: '/specializations/',
  path: '/specializations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBatchesIndexRoute = LiveBatchesIndexRouteImport.update({
  id: '/live-batches/',
  path: '/live-batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsSlugRoute = SpecializationsSlugRouteImport.update({
  id: '/specializations/$slug',
  path: '/specializations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBatchesSlugRoute = LiveBatchesSlugRouteImport.update({
  id: '/live-batches/$slug',
  path: '/live-batches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdmissionsRoute = ApiAdmissionsRouteImport.update({
  id: '/api/admissions',
  path: '/api/admissions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/computer-science-tutoring': typeof ComputerScienceTutoringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-demo': typeof FreeDemoRoute
  '/grade-5-to-ms-online-learning': typeof Grade5ToMsOnlineLearningRoute
  '/international-online-academy': typeof InternationalOnlineAcademyRoute
  '/maths-tutor': typeof MathsTutorRoute
  '/online-classes-for-students': typeof OnlineClassesForStudentsRoute
  '/online-tutor-service-pakistan': typeof OnlineTutorServicePakistanRoute
  '/physics-tutor': typeof PhysicsTutorRoute
  '/privacy': typeof PrivacyRoute
  '/python-course-online': typeof PythonCourseOnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/web-development-course-online': typeof WebDevelopmentCourseOnlineRoute
  '/api/admissions': typeof ApiAdmissionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/live-batches/$slug': typeof LiveBatchesSlugRoute
  '/specializations/$slug': typeof SpecializationsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/live-batches/': typeof LiveBatchesIndexRoute
  '/specializations/': typeof SpecializationsIndexRoute
  '/tutoring/': typeof TutoringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/computer-science-tutoring': typeof ComputerScienceTutoringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-demo': typeof FreeDemoRoute
  '/grade-5-to-ms-online-learning': typeof Grade5ToMsOnlineLearningRoute
  '/international-online-academy': typeof InternationalOnlineAcademyRoute
  '/maths-tutor': typeof MathsTutorRoute
  '/online-classes-for-students': typeof OnlineClassesForStudentsRoute
  '/online-tutor-service-pakistan': typeof OnlineTutorServicePakistanRoute
  '/physics-tutor': typeof PhysicsTutorRoute
  '/privacy': typeof PrivacyRoute
  '/python-course-online': typeof PythonCourseOnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/web-development-course-online': typeof WebDevelopmentCourseOnlineRoute
  '/api/admissions': typeof ApiAdmissionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/live-batches/$slug': typeof LiveBatchesSlugRoute
  '/specializations/$slug': typeof SpecializationsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/live-batches': typeof LiveBatchesIndexRoute
  '/specializations': typeof SpecializationsIndexRoute
  '/tutoring': typeof TutoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/computer-science-tutoring': typeof ComputerScienceTutoringRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-demo': typeof FreeDemoRoute
  '/grade-5-to-ms-online-learning': typeof Grade5ToMsOnlineLearningRoute
  '/international-online-academy': typeof InternationalOnlineAcademyRoute
  '/maths-tutor': typeof MathsTutorRoute
  '/online-classes-for-students': typeof OnlineClassesForStudentsRoute
  '/online-tutor-service-pakistan': typeof OnlineTutorServicePakistanRoute
  '/physics-tutor': typeof PhysicsTutorRoute
  '/privacy': typeof PrivacyRoute
  '/python-course-online': typeof PythonCourseOnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/web-development-course-online': typeof WebDevelopmentCourseOnlineRoute
  '/api/admissions': typeof ApiAdmissionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/live-batches/$slug': typeof LiveBatchesSlugRoute
  '/specializations/$slug': typeof SpecializationsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/live-batches/': typeof LiveBatchesIndexRoute
  '/specializations/': typeof SpecializationsIndexRoute
  '/tutoring/': typeof TutoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/computer-science-tutoring'
    | '/contact'
    | '/faq'
    | '/free-demo'
    | '/grade-5-to-ms-online-learning'
    | '/international-online-academy'
    | '/maths-tutor'
    | '/online-classes-for-students'
    | '/online-tutor-service-pakistan'
    | '/physics-tutor'
    | '/privacy'
    | '/python-course-online'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/web-development-course-online'
    | '/api/admissions'
    | '/courses/$slug'
    | '/live-batches/$slug'
    | '/specializations/$slug'
    | '/courses/'
    | '/live-batches/'
    | '/specializations/'
    | '/tutoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/computer-science-tutoring'
    | '/contact'
    | '/faq'
    | '/free-demo'
    | '/grade-5-to-ms-online-learning'
    | '/international-online-academy'
    | '/maths-tutor'
    | '/online-classes-for-students'
    | '/online-tutor-service-pakistan'
    | '/physics-tutor'
    | '/privacy'
    | '/python-course-online'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/web-development-course-online'
    | '/api/admissions'
    | '/courses/$slug'
    | '/live-batches/$slug'
    | '/specializations/$slug'
    | '/courses'
    | '/live-batches'
    | '/specializations'
    | '/tutoring'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/computer-science-tutoring'
    | '/contact'
    | '/faq'
    | '/free-demo'
    | '/grade-5-to-ms-online-learning'
    | '/international-online-academy'
    | '/maths-tutor'
    | '/online-classes-for-students'
    | '/online-tutor-service-pakistan'
    | '/physics-tutor'
    | '/privacy'
    | '/python-course-online'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/web-development-course-online'
    | '/api/admissions'
    | '/courses/$slug'
    | '/live-batches/$slug'
    | '/specializations/$slug'
    | '/courses/'
    | '/live-batches/'
    | '/specializations/'
    | '/tutoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRoute
  ComputerScienceTutoringRoute: typeof ComputerScienceTutoringRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FreeDemoRoute: typeof FreeDemoRoute
  Grade5ToMsOnlineLearningRoute: typeof Grade5ToMsOnlineLearningRoute
  InternationalOnlineAcademyRoute: typeof InternationalOnlineAcademyRoute
  MathsTutorRoute: typeof MathsTutorRoute
  OnlineClassesForStudentsRoute: typeof OnlineClassesForStudentsRoute
  OnlineTutorServicePakistanRoute: typeof OnlineTutorServicePakistanRoute
  PhysicsTutorRoute: typeof PhysicsTutorRoute
  PrivacyRoute: typeof PrivacyRoute
  PythonCourseOnlineRoute: typeof PythonCourseOnlineRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WebDevelopmentCourseOnlineRoute: typeof WebDevelopmentCourseOnlineRoute
  ApiAdmissionsRoute: typeof ApiAdmissionsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LiveBatchesSlugRoute: typeof LiveBatchesSlugRoute
  SpecializationsSlugRoute: typeof SpecializationsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LiveBatchesIndexRoute: typeof LiveBatchesIndexRoute
  SpecializationsIndexRoute: typeof SpecializationsIndexRoute
  TutoringIndexRoute: typeof TutoringIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-development-course-online': {
      id: '/web-development-course-online'
      path: '/web-development-course-online'
      fullPath: '/web-development-course-online'
      preLoaderRoute: typeof WebDevelopmentCourseOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-course-online': {
      id: '/python-course-online'
      path: '/python-course-online'
      fullPath: '/python-course-online'
      preLoaderRoute: typeof PythonCourseOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-tutor': {
      id: '/physics-tutor'
      path: '/physics-tutor'
      fullPath: '/physics-tutor'
      preLoaderRoute: typeof PhysicsTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-tutor-service-pakistan': {
      id: '/online-tutor-service-pakistan'
      path: '/online-tutor-service-pakistan'
      fullPath: '/online-tutor-service-pakistan'
      preLoaderRoute: typeof OnlineTutorServicePakistanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-classes-for-students': {
      id: '/online-classes-for-students'
      path: '/online-classes-for-students'
      fullPath: '/online-classes-for-students'
      preLoaderRoute: typeof OnlineClassesForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maths-tutor': {
      id: '/maths-tutor'
      path: '/maths-tutor'
      fullPath: '/maths-tutor'
      preLoaderRoute: typeof MathsTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-online-academy': {
      id: '/international-online-academy'
      path: '/international-online-academy'
      fullPath: '/international-online-academy'
      preLoaderRoute: typeof InternationalOnlineAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-5-to-ms-online-learning': {
      id: '/grade-5-to-ms-online-learning'
      path: '/grade-5-to-ms-online-learning'
      fullPath: '/grade-5-to-ms-online-learning'
      preLoaderRoute: typeof Grade5ToMsOnlineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-demo': {
      id: '/free-demo'
      path: '/free-demo'
      fullPath: '/free-demo'
      preLoaderRoute: typeof FreeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-science-tutoring': {
      id: '/computer-science-tutoring'
      path: '/computer-science-tutoring'
      fullPath: '/computer-science-tutoring'
      preLoaderRoute: typeof ComputerScienceTutoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoring/': {
      id: '/tutoring/'
      path: '/tutoring'
      fullPath: '/tutoring/'
      preLoaderRoute: typeof TutoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations/': {
      id: '/specializations/'
      path: '/specializations'
      fullPath: '/specializations/'
      preLoaderRoute: typeof SpecializationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-batches/': {
      id: '/live-batches/'
      path: '/live-batches'
      fullPath: '/live-batches/'
      preLoaderRoute: typeof LiveBatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations/$slug': {
      id: '/specializations/$slug'
      path: '/specializations/$slug'
      fullPath: '/specializations/$slug'
      preLoaderRoute: typeof SpecializationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-batches/$slug': {
      id: '/live-batches/$slug'
      path: '/live-batches/$slug'
      fullPath: '/live-batches/$slug'
      preLoaderRoute: typeof LiveBatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admissions': {
      id: '/api/admissions'
      path: '/api/admissions'
      fullPath: '/api/admissions'
      preLoaderRoute: typeof ApiAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRoute,
  ComputerScienceTutoringRoute: ComputerScienceTutoringRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FreeDemoRoute: FreeDemoRoute,
  Grade5ToMsOnlineLearningRoute: Grade5ToMsOnlineLearningRoute,
  InternationalOnlineAcademyRoute: InternationalOnlineAcademyRoute,
  MathsTutorRoute: MathsTutorRoute,
  OnlineClassesForStudentsRoute: OnlineClassesForStudentsRoute,
  OnlineTutorServicePakistanRoute: OnlineTutorServicePakistanRoute,
  PhysicsTutorRoute: PhysicsTutorRoute,
  PrivacyRoute: PrivacyRoute,
  PythonCourseOnlineRoute: PythonCourseOnlineRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WebDevelopmentCourseOnlineRoute: WebDevelopmentCourseOnlineRoute,
  ApiAdmissionsRoute: ApiAdmissionsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LiveBatchesSlugRoute: LiveBatchesSlugRoute,
  SpecializationsSlugRoute: SpecializationsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LiveBatchesIndexRoute: LiveBatchesIndexRoute,
  SpecializationsIndexRoute: SpecializationsIndexRoute,
  TutoringIndexRoute: TutoringIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
